[package]
name = "story"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "story"
path = "src/story.rs"

[dependencies]
ui.workspace = true
assets.workspace = true
gpui.workspace = true
gpui_platform.workspace = true
anyhow.workspace = true
rust-embed = { version = "8", features = ["include-exclude"] }
strum = { version = "0.27", features = ["derive"] }
